[theme]
primaryColor="#8A0002"
backgroundColor="#d4b1b1"
secondaryBackgroundColor="[theme]
primaryColor="#1a1a1a"
backgroundColor="#E5D5F1"
secondaryBackgroundColor="#EAB9DD"
textColor="#010102"
textColor="#010102"
font="monospace"

